[package]
name = "toml_static"
version = "0.1.0"
authors = ["Zvnlanx <kechaotai@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.118"
serde_derive = "1.0.118"
toml = "0.5.8"
