[package]
name = "templ"
version = "0.1.0"
authors = ["kezt <kztai@insucrm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
serde = "1.0.118"
serde_derive = "1.0.118"
tera = "1.6.1"
